### ISSUE TITLE
Support Lua 5.2

### ISSUE THREAD

**Issue by vschiavoni** [splay-project/splay#2]
Currently the deamon libraries do not compile with Lua 5.2 to to a change in the APIs. 
Errors:

``` Makefile
make -f Makefile.macosx
gcc -Wall -O2 -pedantic -I/opt/local/lib/openssl97/include/ -I/opt/local/include/ -c -o splay_lib.o splay_lib.c
splay_lib.c:47:1: error: unknown type name 'luaL_reg'
splay_lib.c:49:5: warning: braces around scalar initializer [enabled by default]
splay_lib.c:49:5: warning: (near initialization for 'splayd[0]') [enabled by default]
splay_lib.c:49:5: warning: initialization makes integer from pointer without a cast [enabled by default]
splay_lib.c:49:5: warning: (near initialization for 'splayd[0]') [enabled by default]
splay_lib.c:49:5: error: initializer element is not computable at load time
splay_lib.c:49:5: error: (near initialization for 'splayd[0]')
splay_lib.c:49:5: warning: excess elements in scalar initializer [enabled by default]
splay_lib.c:49:5: warning: (near initialization for 'splayd[0]') [enabled by default]
splay_lib.c:50:5: warning: braces around scalar initializer [enabled by default]
splay_lib.c:50:5: warning: (near initialization for 'splayd[1]') [enabled by default]
splay_lib.c:50:5: warning: initialization makes integer from pointer without a cast [enabled by default]
splay_lib.c:50:5: warning: (near initialization for 'splayd[1]') [enabled by default]
splay_lib.c:50:5: warning: excess elements in scalar initializer [enabled by default]
splay_lib.c:50:5: warning: (near initialization for 'splayd[1]') [enabled by default]
splay_lib.c: In function 'new_lua':
splay_lib.c:133:2: warning: implicit declaration of function 'lua_cpcall' [-Wimplicit-function-declaration]
splay_lib.c:142:2: warning: implicit declaration of function 'luaL_openlib' [-Wimplicit-function-declaration]
```
